"""Create place, hechsher and user tables

Revision ID: 334e6721c28e
Revises: 
Create Date: 2026-05-11 03:02:47.120829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334e6721c28e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Hechshers',
    sa.Column('HechsherId', sa.String(length=11), nullable=False),
    sa.Column('HechsherDisplayName', sa.String(length=50), nullable=False),
    sa.Column('HechsherSymbol', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('HechsherId'),
    sa.UniqueConstraint('HechsherDisplayName')
    )
    op.create_table('Places',
    sa.Column('PlaceId', sa.String(length=11), nullable=False),
    sa.Column('PlaceName', sa.String(length=50), nullable=False),
    sa.Column('Coordinates', sa.String(length=50), nullable=True),
    sa.Column('StreetAddress', sa.String(length=255), nullable=True),
    sa.Column('DateAdded', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('PlaceId')
    )
    op.create_table('Users',
    sa.Column('UserId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserEmail', sa.String(length=255), nullable=False),
    sa.Column('UserName', sa.String(length=50), nullable=False),
    sa.Column('UserPassword', sa.String(length=256), nullable=False),
    sa.Column('UserStatus', sa.Enum('admin', 'basic', name='user_status'), nullable=True),
    sa.Column('UserSinceDate', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('UserId')
    )
    op.create_table('HechsherAliases',
    sa.Column('HechsherId', sa.String(length=11), nullable=False),
    sa.Column('HechsherAlias', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['HechsherId'], ['Hechshers.HechsherId'], ),
    sa.PrimaryKeyConstraint('HechsherId', 'HechsherAlias')
    )
    op.create_table('PlaceHechshers',
    sa.Column('PlaceId', sa.String(length=11), nullable=False),
    sa.Column('HechsherId', sa.String(length=11), nullable=False),
    sa.Column('PlaceHechsherMarkingVerity', sa.Enum('verified', 'pending', 'unverified', name='verification_status'), nullable=True),
    sa.ForeignKeyConstraint(['HechsherId'], ['Hechshers.HechsherId'], ),
    sa.ForeignKeyConstraint(['PlaceId'], ['Places.PlaceId'], ),
    sa.PrimaryKeyConstraint('PlaceId', 'HechsherId')
    )
    op.create_table('PlaceTags',
    sa.Column('PlaceId', sa.String(length=11), nullable=False),
    sa.Column('PlaceTag', sa.Enum('restaurant', 'bakery', 'store', 'cafe', 'meat', 'dairy', 'parve', name='place_tag'), nullable=False),
    sa.ForeignKeyConstraint(['PlaceId'], ['Places.PlaceId'], ),
    sa.PrimaryKeyConstraint('PlaceId', 'PlaceTag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PlaceTags')
    op.drop_table('PlaceHechshers')
    op.drop_table('HechsherAliases')
    op.drop_table('Users')
    op.drop_table('Places')
    op.drop_table('Hechshers')
    # ### end Alembic commands ###
